### ISSUE TITLE
Bug in cabling.py

### ISSUE THREAD

**Issue by SolverMax** [hakank/hakank#18]
I'm looking to use OR-Tools to replicate your CPMpy model https://github.com/hakank/hakank/blob/master/cpmpy/cabling.py
Lines 177-179, in the second model, say:
```
  for i in range(n):
    a,b,num = cable_struct[i]
    model += [t[i] == abs(x[a]-x[b])*num]
```
I believe that the range should be:
`  for i in range(len(cable_struct)):
`
The current code returns the correct solution because the example just happens to have `n == len(cable_struct)` but that isn't true in general.

**Comment by hakank** [comment]
@SolverMax  Thanks for your comment. As the problem instance is defined, the definition `n = 8` is used to to create the variables `A`.. `H`, the indices in the definition of `cable_struct` as well as the decision variables `x`, `t`, and `final_sum`. Thus I would say that it's OK to use `range(n)`: 
```
  for i in range(n):
    a,b,num = cable_struct[i]
    model += [t[i] == abs(x[a]-x[b])*num]
```

Using your suggested version (`range(len(cable_struct))`) instead does not make it more general, since the size of `cable_struct` is - by definition, not by accident - the same as `n`.

However, the definition of the specific problem instance could instead have been something like:
```
cable_struct = [[0, 7, 1],
                [0, 4, 2],
                [1, 5, 4],
                [2, 6, 1],
                [2, 3, 1],
                [2, 4, 1],
                [3, 7, 3],
                [6, 7, 1]],
n = len(cable_struct)
% and then the same code ....
```

Personally, I prefer the existing version of definition the problem instance.

**Comment by SolverMax** [comment]
If you define the number of connections to always be the same as the number of devices, then OK. But if we have more connections, then using n doesn't work.
For example, using the 16 device data at https://yurichev.com/blog/cabling requires looping over the number of connections rather than the number of devices.

**Comment by hakank** [comment]
I see your point now. Thanks!

Commit: https://github.com/hakank/hakank/commit/c0655cff647a040e1c87722c3e552404abeb9fe1
