### ISSUE TITLE
An help for Picat

### ISSUE THREAD

**Issue by lparolari** [hakank/hakank#4]
I'm sorry for contacting you here, but I'm having some trouble with Picat and I wish ask you for help if you can.

(the question is not strictly related to this repository)

I'm implementing a solver for [{log}](http://people.dmi.unipr.it/gianfranco.rossi/setlog.Home.html) language in Picat (you can find my code [here](https://github.com/lparolari/setlog-picat)).

### The trouble

I'm parsing a formula given in input by the user with the picat built-in function `parse_term/2`. The formula is made by a list of terms like this: `[eq(X,1), ...]`.
The `parse_term/2` function returns a term representing my formula, but also a map for name of variables and variables themselves.

My objective is to store this map in a global variable and retrieve it when the solver solves the formula to convert back the variables to their original names.

The problem is that I put the map into a global map using `get_global_map().put(k, V)` and then when I retrieve it using `get_global_map().get(k)` the keys of this map are unchanged while values (real variables) have changed.

Why this happens? What I'm doing wrong?

### Code references

Here is where I would convert back variables to their real names:
- [after the solver ended](https://github.com/lparolari/setlog-picat/blob/18572348899360c0d3f906ef5a50d9b25bc3317f/setlog/solver.pi#L38)
- [after each partial result](https://github.com/lparolari/setlog-picat/blob/18572348899360c0d3f906ef5a50d9b25bc3317f/setlog/solver.pi#L62)

And here is the [function](https://github.com/lparolari/setlog-picat/blob/18572348899360c0d3f906ef5a50d9b25bc3317f/setlog/solver.pi#L399) that should convert back variables. Note that this is not working only if I use vars map retrieved from the global map; passing directly the vars map makes this works.

**Comment by hakank** [comment]
Hi Luca.

I'm actually following your {log} language and it's an interesting project (though I haven't played with it much).

However, I would suggest that we discuss this via mail since it's not really about my repo. You are welcome to mail me at hakank@gmail.com. Regarding your problem, I would also appreciate if you could describe a complete "top level" example with inputs etc where you got these problems. It's then much easier for me to test and try to understand exactly what happens.

Best

Hakan
